name: Commit Log

on:
  push:
    branches: ['**']

permissions:
  contents: write

jobs:
  add-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create log file
        run: |
          mkdir -p commit-logs
          echo "Logged commit $GITHUB_SHA on $(date)" > commit-logs/$GITHUB_SHA.log

      - name: Commit and push log file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add commit-logs/$GITHUB_SHA.log
          git commit -m "Add log for $GITHUB_SHA [skip ci]" || echo "No changes to commit"
          git push
